language: node_js
node_js: node

cache:
  yarn: true
  directories:
    - .eslintcache

install:
  - yarn install
script:
  - eslint . --ignore-path .gitignore --cache --cache-location .eslintcache/
  - prettier --check 'data/**/*.json5'

jobs:
  include:
    - stage: deploy
      if: type != pull_request AND branch = master
      script: yarn build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GH_TOKEN
        local-dir: rendered

env:
  global:
    secure: 'hWBeYea3+753TQ3m/572qV6mPY8yoLjqYkVJFcRyF0jv0uCz2Zoij50NwqRz6/tEOOLWw5SGcvpMw+8dvsacvepxMdOfShEhu/IgJtEP9LjfKnAL47YB+UOZMbcyag1PKQNNIjpFnqMJicByKpiTiNpRHwa+63YQky91Eh5MsoD5BETBBoNBfrQLfGKS9SNNxw4QGKMXrg6QU5TQBvmyYfoT0bcD6aNVvlbynTm/8CzF6ElNhxZ5N+ijcMiR8/ncvxyoLCWrkbzE43bsh6gMOxmIsehtHj7LABMERfoAcCAQkdXNm1G40nYRK8CJaaIs0G0AICzw23mY8aU4OoppVWZO4MXAjupN0HqdUR8VlTZmkcXHbhF+9ogdv1ovzQl7MIHEAdWqYM4ju3iTxR5RxEqk1VVYESFe9+cJhd23zWPSqo/VtB2qXejB90R/3MOZHofVzpQpECKPLSP+42TkadT91qsqQZiHXDCghFr9r6XPU+hzp3kieJCPOBVy84CCngsVj21hfAdV1iYlTwn9V/M0aIeSNw/ihKrFAhJHxc5ODVWkD8OuV91FiA0C/S07Nm3XDsfT99VCXFW/MMt0vD4Tumx/zTvWlCnCi4uNexiAlgTBc2EAlxeQtkHdo5jsd0+5S8Ul3WADXDfxxt38fERPtOraBQjcLccHX439Vas='
